language: java
install: true

env:
  global:
    secure: dJBKpFTzWBWDncWeEXJi3KLrJ7bEs6Jciu+ALLmJX4rnBAP6+RTFP3kiZzWJjCU24FkijFawbR/GCMuUZDoQUl2M+8LWHKgqqmdTDHdQqZndmyhKqzz3q+tvsNsHl3P4JKbDDZFzT3y5oz0x3IfclW+spGvBS3kdKuKFGkFe8O9aHZf7CMe6zOaihsRwjpz8gurysvQeH33TjIkI8BujBmxOWr+JnwvGEOpjX+XysEev6GWmlLLe3XZgRdLSilg/lRvB//FWv6WUsXOHV8cs2lC86sKzDQBiQTn5RWWp/1+IBvaMhPCGpIbLzsUvVCZsJZmORbIi3Ly5EY6e+jlOewCveisXNORik/MIXirqPbHmzbLCqAm/H/+gDq1l59xCBvqRGiTkg1UDRJhLTgszgjxiSYlLZ2ioDs97Uh7JyEM4aq0/XZQ+Wpoy4K6mx+31mPfG52X+pQdvnaYaExteguEUda8wisK40N3oamEp0kWOuV5sPyD3iTtmgpaiZ4+4Z6/tLLPl2gYUes3pesLnavFCYrzIG85c1H5Y0cCv73GaLEYHOosF7p31rRMKVjuZiUUDYTklLH7iSSWI7UllzNxALywWw7jXXhJNxrxyji291/fHOrte3s3k60Fo2gpGcNmgwGspdjvDORyIcKyHvghM0RSuTO8LEKWFojnPT3s=

addons:
  ssh_known_hosts: gendercomics.net

before_install:
  - openssl aes-256-cbc -K $encrypted_65c1486ae971_key -iv $encrypted_65c1486ae971_iv -in deploy-key.enc -out deploy-key -d

before_script:
  - VERSION=1.4.0

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gendercomics/api .
  - docker tag gendercomics/api gendercomics/api:latest
  - docker tag gendercomics/api gendercomics/api:$VERSION
  - docker images
  - docker push gendercomics/api:latest
  - docker push gendercomics/api:$VERSION

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_65c1486ae971_key -iv $encrypted_65c1486ae971_iv -in deploy-key.enc -out deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key
  - scp -r ./docker-compose.yml deploy@gendercomics.net:/var/gendercomics/api

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'docker pull gendercomics/api:latest && cd /var/gendercomics/api && docker-compose up -d gendercomics-api-stage'
    on:
      all_branches: true

  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'docker pull gendercomics/api:$VERSION && cd /var/gendercomics/api && docker-compose up -d gendercomics-api'
    on:
      branches: master

notifications:
  slack:
    rooms:
      - visualitiesofgender:3zAI6z6JJXLeEIaBU49O0Wkr#builds
    on_success: change
  email:
    recipients:
      - michael.litschauer@gmail.com
    on_success: always
    on_failure: always
