language: java
install: true

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t gendercomics/api .
        - docker images
        - docker tag gendercomics/api $DOCKER_USERNAME/gendercomics/api
        - docker push $DOCKER_USERNAME/gendercomics/api

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#
#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  on:
#    tags: true
#    all_branches: true
