plugins {
    id 'org.springframework.boot' version '2.7.18'
    id 'com.palantir.docker' version '0.36.0'
    id "io.spring.dependency-management" version "1.1.6"
    id 'java'
    id 'jacoco'
}

group = 'net.gendercomics.api'
version = '2.3.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext {
    junitVersion = '5.11.4'
    keycloakVersion = '6.0.1'
    lombokVersion = '1.18.38'
    springBootVersion = '2.7.18'
    testContainersVersion = '1.20.6'
    swaggerVersion = '2.9.2'
}

ext['jackson.version'] = '2.17.3'
ext['log4j2.version'] = '2.24.3'

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
    compileOnly {
        extendsFrom annotationProcessor
    }
    configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'org.apache.commons' && details.requested.name == 'commons-compress') {
                details.useVersion '1.27.1'
                details.because 'CVE-2024-25710, CVE-2024-26308 fixed in 1.26.0'
            }
        }
    }
}

repositories {
    mavenCentral()
}

springBoot {
    buildInfo()
}


test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    environment 'DOCKER_HOST', 'npipe:////./pipe/docker_engine_linux'
}

jacoco {
    toolVersion = "0.8.13"
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

dependencies {
    // Spring
    implementation "org.springframework.boot:spring-boot-starter-data-mongodb:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-security:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
    developmentOnly "org.springframework.boot:spring-boot-devtools:${springBootVersion}"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor:${springBootVersion}"

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // Jackson
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml"

    // Swagger
    implementation "io.springfox:springfox-swagger2:${swaggerVersion}"
    implementation "io.springfox:springfox-swagger-ui:${swaggerVersion}"

    // Keycloak
    implementation "org.keycloak:keycloak-spring-boot-starter:${keycloakVersion}"

    // Test
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation "org.springframework.security:spring-security-test"
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.keycloak.bom:keycloak-adapter-bom:${keycloakVersion}"
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:deprecation'
    options.compilerArgs << '-Xlint:unchecked'
    options.deprecation = true
}

task unpack(type: Copy) {
    dependsOn bootJar
    from(zipTree(tasks.bootJar.outputs.files.singleFile))
    into("build/dependency")
}

docker {
    name "${project.group}/${bootJar.archiveBaseName}"
    copySpec.from(tasks.unpack.outputs).into("dependency")
    buildArgs(['DEPENDENCY': "dependency"])
}
