version: "3"

services:

  mongodb:
    image: mongo:4.2.10
    container_name: mongodb
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATA_DB: ${MONGO_DATA_DB}
      MONGO_DATA_CONFIGDB: ${MONGO_DATA_CONFIGDB}
    volumes:
      - ${MONGO_DATA_DB}:/data/db
      - ${MONGO_DATA_CONFIGDB}:/data/configdb
    networks:
      - proxy
    ports:
      - 27017:27017
    labels:
      - traefik.enable=false
      - traefik.docker.network=proxy

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA}:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  gendercomics-api-stage:
    image: gendercomics/api:latest
    container_name: gendercomics-api-stage
    restart: always
    environment:
      - HOST
      - SPRING_PROFILES_ACTIVE=stage
      - MONGO_USERNAME=${MONGO_USERNAME_STAGE}
      - MONGO_PASSWORD=${MONGO_PASSWORD_STAGE}
    networks:
      - proxy
    depends_on:
      - mongodb
    labels:
      - traefik.frontend.rule=Host:api-stage.${HOST}
      - traefik.port=8001
      - traefik.docker.network=proxy

  gendercomics-api:
    image: gendercomics/api:1.12.0
    container_name: gendercomics-api
    restart: always
    environment:
      - HOST
      - SPRING_PROFILES_ACTIVE=production
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - proxy
    depends_on:
      - mongodb
    labels:
      - traefik.frontend.rule=Host:api.${HOST}
      - traefik.port=8001
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
  elastic:
    driver: bridge
