version: "3"

services:

#  logstash:
#    image: logstash:${ELK_VERSION}
#    container_name: logstash
#    command: bash -c "cd bin && logstash-plugin install logstash-input-mongodb && logstash-plugin install logstash-output-elasticsearch && logstash -f /usr/share/logstash/config/logstash.conf"
#    environment:
#      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
#    volumes:
#      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
#      - /Users/mike/projects/gendercomics/logstash/:/opt/logstash-mongodb/
#    networks:
#      - elastic
#    depends_on:
#      - elasticsearch
#      - mongodb

#  kibana:
#    image: kibana:${ELK_VERSION}
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_HOSTS: http://localhost:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

  gendercomics-api-stage:
    image: gendercomics/api:latest
    container_name: gendercomics-api-stage
    restart: always
    environment:
      - HOST
      - SPRING_PROFILES_ACTIVE=stage
      - MONGO_USERNAME=${MONGO_USERNAME_STAGE}
      - MONGO_PASSWORD=${MONGO_PASSWORD_STAGE}
    networks:
      - proxy
    depends_on:
      - mongodb
    labels:
      - traefik.frontend.rule=Host:api-stage.${HOST}
      - traefik.port=8001
      - traefik.docker.network=proxy

  gendercomics-api:
    image: gendercomics/api:1.12.1
    container_name: gendercomics-api
    restart: always
    environment:
      - HOST
      - SPRING_PROFILES_ACTIVE=production
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - proxy
    depends_on:
      - mongodb
    labels:
      - traefik.frontend.rule=Host:api.${HOST}
      - traefik.port=8001
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
  data:
    external: true
