version: "3"

services:

  gendercomics-api-stage:
    image: gendercomics/api:latest
    container_name: gendercomics-api-stage
    restart: always
    environment:
      - HOST
      - SPRING_PROFILES_ACTIVE=stage
      - MONGO_USERNAME=${MONGO_USERNAME_STAGE}
      - MONGO_PASSWORD=${MONGO_PASSWORD_STAGE}
    volumes:
      - /var/gendercomics/images-stage/:/images/
    networks:
      - proxy
    labels:
      - traefik.frontend.rule=Host:api-stage.${HOST}
      - traefik.port=8001
      - traefik.docker.network=proxy

  gendercomics-api:
    image: gendercomics/api:1.15.2
    container_name: gendercomics-api
    restart: always
    environment:
      - HOST
      - SPRING_PROFILES_ACTIVE=production
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /var/gendercomics/images/:/images/  
    networks:
      - proxy
    labels:
      - traefik.frontend.rule=Host:api.${HOST}
      - traefik.port=8001
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
