server:
  port: 8001

spring:
  data:
    mongodb:
      uri: mongodb://gendercomics_api:test123@localhost:27017/gendercomics-dev?authSource=admin&authMechanism=SCRAM-SHA-1

keycloak:
  realm: gendercomics
  resource: gendercomics-admin-app
  auth-server-url: http://localhost:9090/auth
  ssl-required: external
  public-client: true
  security-constraints:
    - authRoles:
          - admin
    - securityCollections:
        - name: admin resource
        - patterns:
            - /admin
        - methods:
            - POST
            - PUT
