# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST {{keycloak}}/auth/realms/gendercomics/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=gendercomics-admin&grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiMmZkZDg3ZC1kNmVlLTQ5MmEtYTE5Yy0zN2MzZDI2OThjOGQifQ.eyJqdGkiOiI5OTU3YjU0My1iMDUzLTQ4YmItYmI4ZC1hZjViNmZjZGFhMzQiLCJleHAiOjE1NzE5MTY4MTAsIm5iZiI6MCwiaWF0IjoxNTcxOTE1MDEwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwOTAvYXV0aC9yZWFsbXMvZ2VuZGVyY29taWNzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo5MDkwL2F1dGgvcmVhbG1zL2dlbmRlcmNvbWljcyIsInN1YiI6ImUyNDM3NzRhLTNmZWMtNGQzMS05YzM1LTI4MzVhNjI4YTljNiIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJnZW5kZXJjb21pY3MtYWRtaW4iLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJjNWIyNWZiNi04ZWU3LTQ1OGMtYjk4ZS1mMDFmNWI1NjAzMjYiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImdlbmRlcmNvbWljcy1hZG1pbiI6eyJyb2xlcyI6WyJhZG1pbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIn0.JZzsEmYQVlZLl2NRr3YUytKYi-uhxnsJHg9sWxJfo8M

###