# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Publish Docker image

on: [push]

jobs:
  checkout_repo:
    name: checkout git repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

  push_to_registry:
    needs: checkout_repo
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: gendercomics/api
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  copy_docker_compose:
    needs: [checkout_repo, push_to_registry]
    name: Copy docker-compose.yml to digitalocean.com
    runs-on: ubuntu-latest
    steps:
      - name: SSH Server Deploy
        uses: alinz/ssh-scp-action@master
        env:
          HELLO: cool
          MESSAGE: hello world
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          host: ${{ secrets.APP_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          # runs this on remove server
          ssh_before: |
            echo $HELLO
            echo $MESSAGE
            ls -lath

          # then upload docker-compose.yml
          scp: |
            ./docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.APP_HOST }}:/var/gendercomics/api

          # then run these commands
          ssh_after: |
            echo $HELLO
            echo $MESSAGE
            ls -lath
